name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'helm/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.5'
          cache: true

      - name: Build
        run: go build -o go-web-app

      - name: Run tests
        run: go test -v ./...

  code-quality:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.5'
          cache: true
      
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.57.2
          cache: true

  push-image:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push action
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/go-web-app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  update-chart:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      
      - name: Update chart
        run: |
          if [[ "$OSTYPE" == "darwin"* ]]; then
            # macOS sed command
            sed -i '' "s/tag: .*/tag: ${{ github.sha }}/" helm/go-web-app-chart/values.yaml
          else
            # Linux sed command
            sed -i "s/tag: .*/tag: ${{ github.sha }}/" helm/go-web-app-chart/values.yaml
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "kola0031@algonquinlive.com"
          git config --global user.email "kola0031@algonquinlive.com"
          git add helm/go-web-app-chart/values.yaml
          git commit -m "Update chart tag to ${{ github.sha }}"
          git push

